parameters:
    entreprise: Casas Thomanon

twig:
    globals:
        plantilla: '::base.html.twig'
        entreprise: Casas Thomanon



services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
        - { name: twig.extension }